# ramses_python/__init__.py
__version__ = "0.0.0"
__author__ = "Gain Lee"
__email__ = "gainlee.cosmos@gmail.com"
__url__ = "https://github.com/cosmos-in-us/multiverse_python" # github

"""
Ramses Python Package

This package is designed for the Multiverse-hydro simulation, and also can be used for the HR5 simulation.
It provides tools for reading the binary data generated by the Ramses code, as well as for analyzing the simulation data.

GitHub Repository: https://github.com/cosmos-in-us/multiverse_python
"""

__all__ = ["snapshot", "processing", "newdd"]
from . import *